export const menuData = [
  {
    category: "Soups",
    image: "https://images.unsplash.com/photo-1547592180-85f173990554?auto=format&fit=crop&q=80&w=1200",
    items: [
      { name: "Tomato Soup", price: "₹ 150", type: "veg" },
      { name: "Sweet Corn Veg Soup", price: "₹ 140", type: "veg" },
      { name: "Veg Manchow Soup", price: "₹ 150", type: "veg" },
      { name: "Hot & Sour Veg / Mushroom Soup", price: "₹ 140", type: "veg" },
      { name: "Veg/Mushroom Clear Soup", price: "₹ 140", type: "veg" },
      { name: "Cream Mushroom Soup", price: "₹ 160", type: "veg" },
      { name: "Sweet Corn Chicken Soup", price: "₹ 160", type: "nonveg" },
      { name: "Hot & Sour Chicken Soup", price: "₹ 160", type: "nonveg" },
      { name: "Chicken Clear Soup", price: "₹ 150", type: "nonveg" },
      { name: "Chicken Manchow Soup", price: "₹ 170", type: "nonveg" },
      { name: "Cream Chicken Soup", price: "₹ 170", type: "nonveg" },
      { name: "Hot & Sour Mutton Soup", price: "₹ 190", type: "nonveg" },
    ]
  },
  {
    category: "Veg Starters",
    image: "https://images.unsplash.com/photo-1512621776951-a57141f2eefd?auto=format&fit=crop&q=80&w=1200",
    items: [
      { name: "Aloo Jeera", price: "₹ 220", type: "veg" },
      { name: "Chilli Potato Dry", price: "₹ 280", type: "veg" },
      { name: "Chilli Baby Corn Dry", price: "₹ 280", type: "veg" },
      { name: "Chilli Mushroom Dry", price: "₹ 280", type: "veg" },
      { name: "Chilli Gobi Dry", price: "₹ 280", type: "veg" },
      { name: "Chilli Panner Dry", price: "₹ 310", type: "veg" },
      { name: "Gobi Manchurian Dry", price: "₹ 280", type: "veg" },
      { name: "Mushroom Manchurian Dry", price: "₹ 280", type: "veg" },
      { name: "Baby corn Manchurian Dry", price: "₹ 280", type: "veg" },
      { name: "Veg Manchurian Dry", price: "₹ 280", type: "veg" },
      { name: "Paneer Manchurian Dry", price: "₹ 310", type: "veg" },
      { name: "Schezwan Vegetable Dry", price: "₹ 290", type: "veg" },
      { name: "Mushroom Pepper Fry", price: "₹ 280", type: "veg" },
      { name: "Golden Fried Baby Corn", price: "₹ 280", type: "veg" },
      { name: "Panneer Pakoda", price: "₹ 310", type: "veg" },
      { name: "French Fries", price: "₹ 170", type: "veg" },
      { name: "Masala Pappad", price: "₹ 220", type: "veg" },
      { name: "Roasted Pappad", price: "₹ 50", type: "veg" },
      { name: "Gobi 65", price: "₹ 280", type: "veg" },
    ]
  },
  {
    category: "Non-Veg Starters",
    image: "https://images.unsplash.com/photo-1555939594-58d7cb561ad1?auto=format&fit=crop&q=80&w=1200",
    items: [
      { name: "Chilli Egg Dry", price: "₹ 260", type: "nonveg" },
      { name: "Egg Burge (podimass)", price: "₹ 130", type: "nonveg" },
      { name: "Chicken 65", price: "₹ 340", type: "nonveg" },
      { name: "Pozhichakozhi Fry", price: "₹ 350", type: "nonveg" },
      { name: "Chicken Lollipop (Dry/Saucy)", price: "₹ 340/350", type: "nonveg" },
      { name: "Dragon Chicken", price: "₹ 370", type: "nonveg" },
      { name: "Crispy Fried Chicken", price: "₹ 350", type: "nonveg" },
      { name: "Chicken Bell Pepper Fry", price: "₹ 350", type: "nonveg" },
      { name: "Chicken Kothamalli", price: "₹ 340", type: "nonveg" },
      { name: "Lemon Chicken", price: "₹ 350", type: "nonveg" },
      { name: "Shangai Chicken", price: "₹ 340", type: "nonveg" },
      { name: "Chettinad Chicken Dry", price: "₹ 330", type: "nonveg" },
      { name: "Chicken Pepper Fry", price: "₹ 340", type: "nonveg" },
      { name: "Chicken Chukka", price: "₹ 360", type: "nonveg" },
      { name: "Chilli Chicken Dry", price: "₹ 340", type: "nonveg" },
      { name: "Garlic Chicken Dry", price: "₹ 340", type: "nonveg" },
      { name: "Chicken Manchurian Dry", price: "₹ 340", type: "nonveg" },
      { name: "Schezwan Chicken Dry", price: "₹ 340", type: "nonveg" },
      { name: "Mutton Chukka", price: "₹ 450", type: "nonveg" },
      { name: "Mutton Pepper Fry", price: "₹ 460", type: "nonveg" },
      { name: "Chilli Mutton Fry", price: "₹ 480", type: "nonveg" },
      { name: "Schezwan Mutton Fry", price: "₹ 480", type: "nonveg" },
    ]
  },
  {
    category: "Seafood & Tandoori",
    image: "https://images.unsplash.com/photo-1559742811-822873691df8?auto=format&fit=crop&q=80&w=1200",
    items: [
      { name: "Fish Fry", price: "₹ 440", type: "nonveg" },
      { name: "Fish Finger", price: "₹ 390", type: "nonveg" },
      { name: "Chilli Fish Dry", price: "₹ 390", type: "nonveg" },
      { name: "Fish Manchurian Dry", price: "₹ 390", type: "nonveg" },
      { name: "Nethili Fish Fry", price: "₹ 340", type: "nonveg" },
      { name: "Crispy Squid Rings", price: "₹ 360", type: "nonveg" },
      { name: "Chilli Squid Dry", price: "₹ 390", type: "nonveg" },
      { name: "Fish 65", price: "₹ 390", type: "nonveg" },
      { name: "Prawn Manchurian Dry", price: "₹ 420", type: "nonveg" },
      { name: "Prawn Fry / Pepper Fry", price: "₹ 440", type: "nonveg" },
      { name: "Shangai Prawn", price: "₹ 440", type: "nonveg" },
      { name: "Crab Lollipop", price: "₹ 410", type: "nonveg" },
      { name: "Chilli Crab Fry", price: "₹ 410", type: "nonveg" },
      { name: "Grilled Chicken Half/Full", price: "₹ 360/630", type: "nonveg" },
      { name: "Tandoori Chicken Half/Full", price: "₹ 360/630", type: "nonveg" },
      { name: "Chicken Tikka", price: "₹ 360", type: "nonveg" },
      { name: "Chicken Rangeela Kebab", price: "₹ 390", type: "nonveg" },
      { name: "Chicken Sesame Kebab", price: "₹ 390", type: "nonveg" },
      { name: "Chicken Bannu Kebab", price: "₹ 410", type: "nonveg" },
      { name: "Chicken Kali Mirchi Kebab", price: "₹ 390", type: "nonveg" },
      { name: "Chicken Hariyali Kebab", price: "₹ 390", type: "nonveg" },
      { name: "Chicken Malai Kebab", price: "₹ 390", type: "nonveg" },
      { name: "Chicken Tangri Kebab (3 pcs)", price: "₹ 390", type: "nonveg" },
    ]
  },
  {
    category: "Veg Curries",
    image: "https://images.unsplash.com/photo-1504674900247-0877df9cc836?auto=format&fit=crop&q=80&w=1200",
    items: [
      { name: "Dhal Fry", price: "₹ 240", type: "veg" },
      { name: "Dhal Tadka", price: "₹ 260", type: "veg" },
      { name: "Aloo Gobi Masala", price: "₹ 280", type: "veg" },
      { name: "Green Peas Masala", price: "₹ 280", type: "veg" },
      { name: "Channa Masala", price: "₹ 280", type: "veg" },
      { name: "Mix Veg Curry", price: "₹ 290", type: "veg" },
      { name: "Kadai Vegetable", price: "₹ 280", type: "veg" },
      { name: "Kadai Mushroom", price: "₹ 290", type: "veg" },
      { name: "Mushroom Masala", price: "₹ 290", type: "veg" },
      { name: "Kadai Paneer", price: "₹ 290", type: "veg" },
      { name: "Mutter Paneer", price: "₹ 310", type: "veg" },
      { name: "Paneer Butter Masala", price: "₹ 390", type: "veg" },
      { name: "Veg Kofta", price: "₹ 380", type: "veg" },
      { name: "Malai Kofta", price: "₹ 390", type: "veg" },
      { name: "Paneer Pasinda", price: "₹ 390", type: "veg" },
    ]
  },
  {
    category: "Non-Veg Curries",
    image: "https://images.unsplash.com/photo-1588166524941-3bf61a9c41db?auto=format&fit=crop&q=80&w=1200",
    items: [
      { name: "Egg Masala", price: "₹ 230", type: "nonveg" },
      { name: "Egg Burge Masala", price: "₹ 240", type: "nonveg" },
      { name: "Chicken Curry", price: "₹ 330", type: "nonveg" },
      { name: "Chettinad Chicken Curry", price: "₹ 330", type: "nonveg" },
      { name: "Pepper Chicken Gravy", price: "₹ 340", type: "nonveg" },
      { name: "Butter Chicken Masala", price: "₹ 390", type: "nonveg" },
      { name: "Kadai Chicken", price: "₹ 360", type: "nonveg" },
      { name: "Chicken Dopiyaza", price: "₹ 360", type: "nonveg" },
      { name: "Chicken Rogan Josh", price: "₹ 390", type: "nonveg" },
      { name: "Chicken Punjabi", price: "₹ 360", type: "nonveg" },
      { name: "Hyderabadi Chicken Gravy", price: "₹ 390", type: "nonveg" },
      { name: "Chicken Mughali (sweet)", price: "₹ 410", type: "nonveg" },
      { name: "Naatukozhi Gravy", price: "₹ 460", type: "nonveg" },
      { name: "Chettinad Mutton Gravy", price: "₹ 470", type: "nonveg" },
      { name: "Chettinad Mutton Pepper Gravy", price: "₹ 470", type: "nonveg" },
      { name: "Kadai Mutton", price: "₹ 470", type: "nonveg" },
      { name: "Mutton Punjabi", price: "₹ 470", type: "nonveg" },
      { name: "Mutton Rogan Josh", price: "₹ 470", type: "nonveg" },
      { name: "Chettinad Prawn Masala", price: "₹ 410", type: "nonveg" },
      { name: "Kadai Prawn", price: "₹ 430", type: "nonveg" },
    ]
  },
  {
    category: "Main Course & Rice",
    image: "https://images.unsplash.com/photo-1585032226651-759b368d7246?auto=format&fit=crop&q=80&w=1200",
    items: [
      { name: "Veg Fried Rice", price: "₹ 220", type: "veg" },
      { name: "Mushroom Fried Rice", price: "₹ 240", type: "veg" },
      { name: "Panner Fried Rice", price: "₹ 260", type: "veg" },
      { name: "Mixed Veg Fried Rice", price: "₹ 250", type: "veg" },
      { name: "Egg Fried Rice", price: "₹ 240", type: "nonveg" },
      { name: "Chicken Fried Rice", price: "₹ 290", type: "nonveg" },
      { name: "Mutton Fried Rice", price: "₹ 390", type: "nonveg" },
      { name: "Prawn Fried Rice", price: "₹ 340", type: "nonveg" },
      { name: "Mix Non-Veg Fried Rice", price: "₹ 400", type: "nonveg" },
      { name: "Veg Pulav", price: "₹ 260", type: "veg" },
      { name: "Panner Pulav", price: "₹ 270", type: "veg" },
      { name: "Cashew Nut Pulav", price: "₹ 310", type: "veg" },
      { name: "Green Peas Pulav", price: "₹ 260", type: "veg" },
      { name: "Steam Rice", price: "₹ 110", type: "veg" },
      { name: "Jeera Rice", price: "₹ 210", type: "veg" },
      { name: "Ghee Rice", price: "₹ 240", type: "veg" },
      { name: "Veg Noodles", price: "₹ 220", type: "veg" },
      { name: "Mushroom Noodles", price: "₹ 240", type: "veg" },
      { name: "Panner Noodles", price: "₹ 260", type: "veg" },
      { name: "Mixed Veg Noodles", price: "₹ 250", type: "veg" },
      { name: "Egg Fried Noodles", price: "₹ 240", type: "nonveg" },
      { name: "Chicken Noodles", price: "₹ 270", type: "nonveg" },
      { name: "Mutton Noodles", price: "₹ 390", type: "nonveg" },
      { name: "Prawn Noodles", price: "₹ 340", type: "nonveg" },
      { name: "Mix Non-Veg Noodles", price: "₹ 400", type: "nonveg" },
      { name: "America Chopseuy Veg/Non-Veg", price: "₹ 330/390", type: "nonveg" },
    ]
  },
  {
    category: "Biriyani",
    image: "https://images.unsplash.com/photo-1631515243349-e0cb75fb8d3a?auto=format&fit=crop&q=80&w=1200",
    items: [
      { name: "Chicken Biriyani", price: "₹ 290", type: "nonveg" },
      { name: "Mutton Biriyani", price: "₹ 390", type: "nonveg" },
      { name: "Spl Chicken Biriyani (Ch 65 boneless)", price: "₹ 330", type: "nonveg" },
      { name: "Prawn Biriyani", price: "₹ 330", type: "nonveg" },
      { name: "Fish 65 Biriyani", price: "₹ 350", type: "nonveg" },
      { name: "Egg Biriyani", price: "₹ 240", type: "nonveg" },
    ]
  },
  {
    category: "Breads",
    image: "https://images.unsplash.com/photo-1509440159596-0249088772ff?auto=format&fit=crop&q=80&w=1200",
    items: [
      { name: "Plain Roti", price: "₹ 60", type: "veg" },
      { name: "Butter Roti", price: "₹ 70", type: "veg" },
      { name: "Tandoori Paratha", price: "₹ 80", type: "veg" },
      { name: "Butter Paratha", price: "₹ 80", type: "veg" },
      { name: "Pudina Paratha", price: "₹ 80", type: "veg" },
      { name: "Chappathi", price: "₹ 50", type: "veg" },
      { name: "Plain Naan", price: "₹ 60", type: "veg" },
      { name: "Butter Naan", price: "₹ 70", type: "veg" },
      { name: "Garlic Naan", price: "₹ 80", type: "veg" },
      { name: "Plain Kulcha", price: "₹ 70", type: "veg" },
      { name: "Panner Kulcha", price: "₹ 90", type: "veg" },
      { name: "Masala Kulcha", price: "₹ 90", type: "veg" },
      { name: "Onion Kulcha", price: "₹ 80", type: "veg" },
      { name: "Methi Kulcha", price: "₹ 80", type: "veg" },
      { name: "Pudina Kulcha", price: "₹ 80", type: "veg" },
      { name: "Tawa Paratha", price: "₹ 50", type: "veg" },
    ]
  },
  {
    category: "Desserts & Beverages",
    image: "https://images.unsplash.com/photo-1551024601-bec78aea704b?auto=format&fit=crop&q=80&w=1200",
    items: [
      { name: "Carrot Halwa / with Ice Cream", price: "₹ 90/120", type: "veg" },
      { name: "Gulab Jamun / with Ice Cream", price: "₹ 60/90", type: "veg" },
      { name: "Brownie / with Ice Cream", price: "₹ 90/120", type: "veg" },
      { name: "Vanilla Ice cream", price: "₹ 70", type: "veg" },
      { name: "Butterscotch Ice cream", price: "₹ 80", type: "veg" },
      { name: "Strawberry Ice cream", price: "₹ 80", type: "veg" },
      { name: "Mango Ice cream", price: "₹ 80", type: "veg" },
      { name: "Chocolate Ice cream", price: "₹ 80", type: "veg" },
      { name: "Cassata Slice", price: "₹ 80", type: "veg" },
      { name: "Black Currant Icecream", price: "₹ 80", type: "veg" },
      { name: "Pista Icecream", price: "₹ 80", type: "veg" },
      { name: "Fresh Lemon Soda", price: "₹ 50", type: "veg" },
      { name: "Fresh Lemon Juice", price: "₹ 50", type: "veg" },
      { name: "Sweet Lassi", price: "₹ 70/110", type: "veg" },
      { name: "Mineral Water", price: "₹ 25", type: "veg" },
      { name: "Soft Drinks", price: "₹ 20", type: "veg" },
    ]
  }
];
